project:
  type: website
  output-dir: docs

website:
  title: Celine Wuyts
  favicon: kuleuven.ico

  navbar:
    left:
      - text: About me
        href: index.qmd
      - text: CV
        href: "_assets/wuyts_celine_cv_web.pdf"
      - text: Current projects
        href: current_projects.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/celine-wuyts-79312660
      - text: "{{< ai researchgate >}}"
        href: https://www.researchgate.net/profile/Celine-Wuyts
      - icon: envelope
        href: mailto:celine_w@alum.mit.edu
        
    
  page-footer: 
   left: A [Quarto](https://quarto.org/) website
   right: Donate to the [GiveWell Top Charities Fund](https://www.givewell.org/) today!

format:
  html:
    theme: 
      - flatly
      - styles.scss
    email-obfuscation: references


